### ISSUE TITLE
Samenwerken op Github

### ISSUE THREAD

**Issue by KoopReynders** [FatimaZelay/Squadpage#5]
Lees de instructies van de leertaak zorgvuldig door. Daar staat goede uitleg die je helpt bij het opzetten van een project. 

Jullie kunnen werken in mapjes op dezelfde repo (niet in branches). Alle teamleden kunnen daarin werken aan hun eigen versie. Later kan je met je team één website maken van de verschillende versies die jullie hebben gemaakt.

**Comment by Karima002** [comment]
commit  27c743d
commit 0a73988

**Comment by KoopReynders** [comment]
Mooi een issue gesloten! 
Goed dat je naar een commit linkt, schrijf de volgend keer ook een kort tekstje met wat je hebt gedaan, dan weet je zelf en anderen wat er is gebeurd!
